steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/icmaa-shop-imp-test-01/vue-storefront', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/icmaa-shop-imp-test-01/vue-storefront' ]
