steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-docker.pkg.dev/icmaa-shop-imp-prod-01/eu.gcr.io/vue-storefront', '-f', 'docker/google-cloud-run/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-docker.pkg.dev/icmaa-shop-imp-prod-01/eu.gcr.io/vue-storefront' ]
