apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/icmaa-shop-imp-test-01/vue-storefront@sha256:a9e7282795583b63bd74f9fa0b5edc538f5223d815e1a0902c11048511383cbe
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west3
  name: vue-storefront
  namespace: '650622667513'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/vpc-access-connector: projects/icmaa-shop-imp-test-01/locations/europe-west3/connectors/default
        run.googleapis.com/vpc-access-egress: private-ranges-only
      name: vue-storefront-00002-gup
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: VSF_SERVER_HOST
          value: 0.0.0.0
        - name: VSF_SERVER_PORT
          value: $PORT
        - name: NODE_APP_INSTANCE
          value: imp
        - name: NODE_CONFIG_ENV
          value: test
        image: gcr.io/icmaa-shop-imp-test-01/vue-storefront@sha256:a9e7282795583b63bd74f9fa0b5edc538f5223d815e1a0902c11048511383cbe
        ports:
        - containerPort: 3000
          name: http1
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
      serviceAccountName: 650622667513-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
