version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    volumes:
      - './node_modules:/var/www/node_modules'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './src:/var/www/src'
      - './packages:/var/www/packages'
      - './var:/var/www/var'
      - './babel.config.json:/var/www/babel.config.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './.huskyrc.js:/var/www/.huskyrc.js'
      - './.jshintrc:/var/www/.jshintrc'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'
      - '9229:9229'
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
