export const ICMAA_SEARCHALIAS_ADD = 'ADD_SEARCHALIAS'
export const ICMAA_SEARCHALIAS_UPD = 'UPDATE_SEARCHALIAS'
export const ICMAA_SEARCHALIAS_RMV = 'REMOVE_SEARCHALIAS'
export const ICMAA_SEARCHALIAS_SET_CURRENT_TERM = 'SET_CURRENT_TERM'
