export const SN_ICMAA_CONFIG = 'ICMAA_CONFIG'
export const ICMAA_CONFIG_ADD_MAP = `${SN_ICMAA_CONFIG}/ADD_MAP`
export const ICMAA_CONFIG_SET_CURRENT_STOREVIEW = `${SN_ICMAA_CONFIG}/SET_CURRENT_STOREVIEW`
