export const SN_ICMAA_RECOMMENDATIONS = 'ICMAA_RECOMMENDATIONS'
export const ICMAA_RECOMMENDATIONS_ADD = `${SN_ICMAA_RECOMMENDATIONS}/ADD`
export const ICMAA_RECOMMENDATIONS_SET_RULES = `${SN_ICMAA_RECOMMENDATIONS}/SET_RULES`
