import config from 'config'
import serveStatic from 'serve-static'
import mime from 'mime/lite'
import { createServer, IncomingMessage, OutgoingMessage, ServerResponse } from 'http'
import { createApp, useQuery, useMethod, Handle, createError, sendError, send, sendRedirect } from 'h3'
import { serverHooksExecutors } from '@vue-storefront/core/server/hooks'
import { storeCodeFromUrlPath } from 'icmaa-config/helpers/store'
import { Context } from './utils/types'

const path = require('path')
const glob = require('glob')
const rootPath = require('app-root-path').path
const cache = require('./utils/cache-instance')
const themeRootPath = require('../build/theme-path')
const compilationPage = require('../pages/Compilation')
const ssr = require('./utils/ssr-renderer')
const resolve = file => path.resolve(rootPath, file)
const isProd = process.env.NODE_ENV === 'production'

/** Load server extensions */
const serverExtensions = glob.sync('src/modules/*/server.js')
const configProviders: Function[] = []
serverExtensions.map(serverModule => {
  const module = require(resolve(serverModule))
  if (module.configProvider && typeof module.configProvider === 'function') {
    configProviders.push(module.configProvider)
  }
})

serverHooksExecutors.afterProcessStarted(config.server)

const app = createApp()

serverHooksExecutors.afterApplicationInitialized({ app, config: config.server, isProd })

const staticRoutes = {
  '/assets': `${themeRootPath}/assets`,
  '/dist': `${rootPath}/dist`,
  '/service-worker.js': `${rootPath}/dist/service-worker.js`,
  '/service-worker.js.map': `${rootPath}/dist/service-worker.js.map`,
  '/cache-version.json': `${rootPath}/core/build/cache-version.json`
}

export const serveStaticMiddleware = function (path: string) {
  return (req: IncomingMessage, res: OutgoingMessage, next) => {
    const mimeType = mime.getType(path + req.url)
    let maxAge = config.expireHeaders.default;
    if (config.expireHeaders.hasOwnProperty(mimeType)) {
      maxAge = config.expireHeaders.get(mimeType);
    }
    return serveStatic(path, { maxAge })(req as any, res as any, next) as Handle
  }
}

Object.entries(staticRoutes).forEach(([routePath, staticPath]) => {
  app.use(routePath, serveStaticMiddleware(staticPath))
})

/** @todo Handle invalidate requests */
// app.post('/invalidate', invalidateCache)
// app.get('/invalidate', invalidateCache)

app.use((req) => {
  console.log(
    Date.now(),
    useMethod(req),
    req.url,
    useQuery(req)
  )
})

let renderer
// let globalContextConfig: any = null;
const NOT_ALLOWED_SSR_EXTENSIONS_REGEX = new RegExp(`^.*\\.(${config.server.ssrDisabledFor.extensions.join('|')})$`)
const compileOptions = {
  escape: /{{([^{][\s\S]+?[^}])}}/g,
  interpolate: /{{{([\s\S]+?)}}}/g
}

const templatesCache = ssr.initTemplatesCache(config, compileOptions)

if (isProd) {
  // In production: create server renderer using server bundle and index HTML
  // template from real fs.
  // The server bundle is generated by vue-ssr-webpack-plugin.
  const clientManifest = require(resolve('dist/vue-ssr-client-manifest.json'))
  const bundle = require(resolve('dist/vue-ssr-bundle.json'))
  // src/index.template.html is processed by html-webpack-plugin to inject
  // build assets and output as dist/index.html.
  // TODO: Add dynamic templates loading from (config based?) list
  renderer = ssr.createRenderer(bundle, clientManifest)
} else {
  // In development: setup the dev server with watch and hot-reload,
  // and create a new renderer on bundle / index template update.
  require(resolve('core/build/dev-server'))(app, (bundle, template) => {
    templatesCache['default'] = ssr.compileTemplate(template, compileOptions) // Important Notice: template switching doesn't work with dev server because of the HMR
    renderer = ssr.createRenderer(bundle)
  })
}

const apiStatus = async (res: ServerResponse, data, statusCode = 200, dropExcp = true) => {
  if (statusCode > 400) {
    if (dropExcp) {
      const statusMessage = typeof data === 'string' ? data : undefined
      const err = createError({ statusCode, statusMessage, data })
      return sendError(res, err, !isProd)
    }
    res.statusCode = statusCode
  }

  return res.end(data)
}

app.use('*', async (req, res) => {
  if (NOT_ALLOWED_SSR_EXTENSIONS_REGEX.test(req.url)) {
    apiStatus(res, `The resource ${req.url} couldn't be served using the VSF server`, 404)
    return
  }

  const s = Date.now()

  const site = req.headers['x-vs-store-code'] as string || 'main';
  const currentKey = `page:${site}:${req.url}`;
  const newCacheKey = serverHooksExecutors.beforeBuildCacheKey({ currentKey, req, site })
  const cacheKey = typeof newCacheKey === 'string' ? newCacheKey : currentKey;

  const errorHandler = err => {
    if (err && err.code === 404) {
      console.error(`Redirect for resource not found: ${req.url}`)
      return sendRedirect(res, '/page-not-found')
    } else {
      console.error(`Error during render : ${req.url}`)
      if (!isProd) console.error(err)

      serverHooksExecutors.ssrException({ err, req, isProd })
      const storeCode = storeCodeFromUrlPath(req.url)
      return sendRedirect(res, storeCode ? `/${storeCode}/error` : '/error')
    }
  }

  const dynamicRequestHandler = async (renderer, config) => {
    if (!renderer) {
      return send(res, compilationPage, 'text/html')
    }

    const context: Context = ssr.initSSRRequestContext(app, req, res, config)
    return renderer.renderToString(context).then(output => {
      if (context.server._redirect.isPending()) {
        console.log(`Redirect from [${context.url}]`)
        context.server._redirect.resolver.call(null)
        return
      }

      if (!res.getHeader('content-type')) {
        res.setHeader('Content-Type', 'text/html')
      }

      let tagsArray = []
      if (config.server.useOutputCacheTagging && context.output.cacheTags && context.output.cacheTags.size > 0) {
        tagsArray = Array.from(context.output.cacheTags)
        const cacheTags = tagsArray.join(' ')
        res.setHeader('X-VS-Cache-Tags', cacheTags)
        console.log(`Cache tags for the request: ${cacheTags}`)
      }

      const beforeOutputRenderedResponse = serverHooksExecutors.beforeOutputRenderedResponse({
        req,
        res,
        context,
        output,
        isProd
      })

      if (typeof beforeOutputRenderedResponse.output === 'string') {
        output = beforeOutputRenderedResponse.output
      } else if (typeof beforeOutputRenderedResponse === 'string') {
        output = beforeOutputRenderedResponse
      }

      output = ssr.applyAdvancedOutputProcessing(context, output, templatesCache, isProd);

      if (config.server.useOutputCache && cache) {
        cache.set(
          cacheKey,
          { headers: res.getHeaders(), body: output, httpCode: res.statusCode },
          tagsArray
        ).catch(err => {
          console.error('Couldn\'t write output-cache:', err.message)
        })
      }

      const afterOutputRenderedResponse = serverHooksExecutors.afterOutputRenderedResponse({
        req,
        res,
        context,
        output,
        isProd
      })

      if (typeof afterOutputRenderedResponse === 'string') {
        return afterOutputRenderedResponse
      } else if (typeof afterOutputRenderedResponse.output === 'string') {
        return afterOutputRenderedResponse.output
      } else {
        return output
      }
    })
  }

  const dynamicCacheHandler = async (config) => {
    if (config.server.useOutputCache && cache) {
      return cache.get(
        cacheKey
      ).then(async output => {
        if (output !== null) {
          if (output.headers) {
            for (const header of Object.keys(output.headers)) {
              res.setHeader(header, output.headers[header])
            }
          }
          res.setHeader('X-VS-Cache', 'Hit')

          if (output.body) {
            apiStatus(res, output.body, output.httpCode, false)
          } else {
            res.setHeader('Content-Type', 'text/html')
            apiStatus(res, output, output.httpCode, false)
          }

          console.log(`Cache hit [${req.url}], cached request: ${Date.now() - s}ms`)
        } else {
          res.setHeader('X-VS-Cache', 'Miss')
          console.log(`Cache miss [${req.url}], request: ${Date.now() - s}ms`)
          apiStatus(res, await dynamicRequestHandler(renderer, config), null, false)
        }
      }).catch(errorHandler)
    } else {
      await apiStatus(res, dynamicRequestHandler(renderer, config))
    }
  }

  return dynamicCacheHandler(config)
})

const port = process.env.PORT || config.server.port
const host = process.env.HOST || config.server.host

createServer(app)
  .listen(process.env.PORT || 3000, host)
  .on('listening', () => {
    console.log('VueStorefront server started at:', `http://${host}:${port}`)
  })
  .on('error', (e) => {
    if ((e as any).code === 'EADDRINUSE') {
      console.log(`The port ${port} is already in use`)
    }
  })
