import config from 'config'
import serveStatic from 'serve-static'
import mime from 'mime/lite'
import { createServer, IncomingMessage, OutgoingMessage, ServerResponse } from 'http'
import { createApp, useQuery, useMethod, Handle, assertMethod, createError, sendError, send } from 'h3'
import { serverHooksExecutors } from '@vue-storefront/core/server/hooks'

const path = require('path')
const glob = require('glob')
const rootPath = require('app-root-path').path
const themeRootPath = require('../build/theme-path')
const ssr = require('./utils/ssr-renderer')
const resolve = file => path.resolve(rootPath, file)
const isProd = process.env.NODE_ENV === 'production'

/** Load server extensions */
const serverExtensions = glob.sync('src/modules/*/server.js')
const configProviders: Function[] = []
serverExtensions.map(serverModule => {
  const module = require(resolve(serverModule))
  if (module.configProvider && typeof module.configProvider === 'function') {
    configProviders.push(module.configProvider)
  }
})

serverHooksExecutors.afterProcessStarted(config.server)

const app = createApp()

serverHooksExecutors.afterApplicationInitialized({ app, config: config.server, isProd })

const staticRoutes = {
  '/assets': `${themeRootPath}/assets`,
  '/dist': `${rootPath}/dist`,
  '/service-worker.js': `${rootPath}/dist/service-worker.js`,
  '/service-worker.js.map': `${rootPath}/dist/service-worker.js.map`,
  '/cache-version.json': `${rootPath}/core/build/cache-version.json`
}

export const serveStaticMiddleware = function (path: string) {
  return (req: IncomingMessage, res: OutgoingMessage, next) => {
    const mimeType = mime.getType(path + req.url)
    let maxAge = config.expireHeaders.default;
    if (config.expireHeaders.hasOwnProperty(mimeType)) {
      maxAge = config.expireHeaders.get(mimeType);
    }
    return serveStatic(path, { maxAge })(req as any, res as any, next) as Handle
  }
}

Object.entries(staticRoutes).forEach(([routePath, staticPath]) => {
  app.use(routePath, serveStaticMiddleware(staticPath))
})

/** @todo Handle invalidate requests */
// app.post('/invalidate', invalidateCache)
// app.get('/invalidate', invalidateCache)

app.use((req) => {
  console.log(
    Date.now(),
    useMethod(req),
    req.url,
    useQuery(req)
  )
})

// let renderer
// let globalContextConfig: any = null;
const NOT_ALLOWED_SSR_EXTENSIONS_REGEX = new RegExp(`^.*\\.(${config.server.ssrDisabledFor.extensions.join('|')})$`)
// const compileOptions = {
//   escape: /{{([^{][\s\S]+?[^}])}}/g,
//   interpolate: /{{{([\s\S]+?)}}}/g
// }

// const templatesCache = ssr.initTemplatesCache(config, compileOptions)

// if (isProd) {
//   // In production: create server renderer using server bundle and index HTML
//   // template from real fs.
//   // The server bundle is generated by vue-ssr-webpack-plugin.
//   const clientManifest = require(resolve('dist/vue-ssr-client-manifest.json'))
//   const bundle = require(resolve('dist/vue-ssr-bundle.json'))
//   // src/index.template.html is processed by html-webpack-plugin to inject
//   // build assets and output as dist/index.html.
//   // TODO: Add dynamic templates loading from (config based?) list
//   renderer = ssr.createRenderer(bundle, clientManifest)
// } else {
//   // In development: setup the dev server with watch and hot-reload,
//   // and create a new renderer on bundle / index template update.
//   require(resolve('core/build/dev-server'))(app, (bundle, template) => {
//     templatesCache['default'] = ssr.compileTemplate(template, compileOptions) // Important Notice: template switching doesn't work with dev server because of the HMR
//     renderer = ssr.createRenderer(bundle)
//   })
// }

const apiStatus = async (res: ServerResponse, data, statusCode = 200) => {
  if (statusCode > 400) {
    const statusMessage = typeof data === 'string' ? data : undefined
    const err = createError({ statusCode, statusMessage, data })
    return sendError(res, err, !isProd)
  }
  return res.end(data)
}

app.use('*', async (req, res) => {
  if (NOT_ALLOWED_SSR_EXTENSIONS_REGEX.test(req.url)) {
    apiStatus(res, `The resource ${req.url} couldn't be served using the VSF server`, 404)
    return
  }

  const s = Date.now()
  apiStatus(res, `${s}`)
})

let port = process.env.PORT || config.server.port
const host = process.env.HOST || config.server.host

createServer(app)
  .listen(process.env.PORT || 3000, host)
  .on('listening', () => {
    console.log('VueStorefront server started at:', `http://${host}:${port}`)
  })
  .on('error', (e) => {
    if ((e as any).code === 'EADDRINUSE') {
      console.log(`The port ${port} is already in use`)
    }
  })
