name: Continuous Delivery

on:
  push:
    branches:
      - master
      - master-*
      - develop
      - develop-*
      - build/*

jobs:

  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - MANDANT: imp

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Get repository-name, branch-name and version-name
        run: |
          echo "APP=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "VERSION_NAME=$(echo $(echo ${GITHUB_REF#refs/heads/} | cut -c -52)-$(git rev-parse --short ${GITHUB_SHA}) | sed -e 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV

      - name: Get environment by branch
        run: |
          echo "ENV=$(if [[ ${{ env.BRANCH_NAME }} =~ ^master ]]; then echo "production"; else echo "test"; fi)" >> $GITHUB_ENV

      - name: Checkout "icmaa/shop-workspace" repo
        run: |
          rm -rf shop-workspace
          export CONFIG_BRANCH=$(if [[ ${{ env.BRANCH_NAME }} =~ ^master ]]; then echo "-b master"; else echo "-b develop"; fi)
          git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

      - name: Sync config JSON files
        run: rsync -r ./shop-workspace/template/${{ env.APP }}/ ./

      - name: Build "${{ env.APP }}"
        run: yarn build
        env:
          NODE_CONFIG_ENV: ${{ env.ENV }}
          NODE_APP_INSTANCE: ${{ matrix.env.MANDANT }}

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ env.ENV == 'production' && secrets.GCP_VSF_SA_KEY_PROD || secrets.GCP_VSF_SA_KEY_TEST }}
          deliverables: app-${{ matrix.env.MANDANT }}-${{ env.ENV == 'production' && 'prod' || 'test' }}.yaml
          version: ${{ env.VERSION_NAME }}
          promote: ${{ env.ENV == 'production' && 'false' || 'true' }}
