name: Continuous Integration

on:
  push:
    # paths:
    #   - 'core/**'
    #   - 'packages/**'
    #   - 'src/**'
    # branches:
    #   - master
    #   - develop
    #   - tests/*

env:
  NODE_APP_INSTANCE: "imp"
  NODE_CONFIG_ENV: "test"
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  CI_TESTS: true

jobs:

  # test-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - name: Run ESlint
  #       run: |
  #         yarn
  #         yarn lint

  # test-unit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - name: Checkout "icmaa/vue-storefront-workspace" repo
  #       run: |
  #         git clone --no-tags --depth 1 https://${{ secrets.GITHUB_PAT }}@github.com/icmaa/vue-storefront-workspace
  #     - name: Sync config JSON files
  #       run: rsync -r ./vue-storefront-workspace/template/vue-storefront/ ./
  #     - name: Run Jest-Unit-Tests
  #       run: |
  #         yarn
  #         yarn test:unit

  tests-e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [ 'runner-1', 'runner-2', 'runner-3', 'runner-4' ]
    
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Checkout "icmaa/vue-storefront-workspace" repo
        run: |
          git clone --no-tags --depth 1 https://${{ secrets.GITHUB_PAT }}@github.com/icmaa/vue-storefront-workspace

      - name: Sync config JSON files
        run: rsync -r ./vue-storefront-workspace/template/vue-storefront/ ./
      
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Start
        run: yarn pm2 start ecosystem.ci.json

      - name: Cypress run
        uses: cypress-io/github-action@v1
        timeout-minutes: 7
        with:
          install: false
          working-directory: src/themes/icmaa-imp/test/e2e
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          headless: true
          record: true
          parallel: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_PROJECT_ID: ${{secrets.CYPRESS_PROJECT_ID}}
