name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  NODE_APP_INSTANCE: "imp"
  NODE_CONFIG_ENV: "test"
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  CI_TESTS: true

jobs:

  test-lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Run ESlint
        run: |
          yarn lint

  test-unit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Checkout "icmaa/shop-workspace" repo
        run: |
          rm -rf shop-workspace
          export CONFIG_BRANCH=$(if [[ ${{ github.base_ref }} =~ ^master ]]; then echo "-b master"; else echo "-b develop"; fi)
          git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

      - name: Sync config JSON files
        run: rsync -r ./shop-workspace/template/vue-storefront/ ./

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Run Jest-Unit-Tests
        run: |
          yarn test:unit

  tests-e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [ 'runner-1', 'runner-2', 'runner-3', 'runner-4', 'runner-5' ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Checkout "icmaa/shop-workspace" repo
        run: |
          rm -rf shop-workspace
          export CONFIG_BRANCH=$(if [[ ${{ github.base_ref }} =~ ^master ]]; then echo "-b master"; else echo "-b develop"; fi)
          git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

      - name: Sync config JSON files
        run: rsync -r ./shop-workspace/template/vue-storefront/ ./

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Start
        env:
          VSF_REDIS_HOST: localhost
          VSF_SERVER_PORT: 6379
          VSF_STORYBLOK_RELEASE_ID: ${{ secrets.STORYBLOK_RELEASE_ID }}
        run: |
          yarn pm2 start ecosystem.ci.json

      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        timeout-minutes: 5
        with:
          working-directory: src/themes/icmaa-imp/test/e2e
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          headless: true
          config: video=true
          # spec: integration/Cms/**/*
          record: true
          parallel: true
          group: ${{ runner.os }}
          tag: ${{ github.event_name }},${{ github.event_name }}/${{ github.event.action }}
          ci-build-id: 'continous-integration-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}'
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_PROJECT_ID: ${{secrets.CYPRESS_PROJECT_ID}}

      - name: Dump and consolidate outputs
        if: failure()
        run: |
          mkdir artifacts
          yarn pm2 logs --format --nostream --lines 10000000 > artifacts/server.log
          rsync -avzr --ignore-missing-args src/themes/icmaa-imp/test/e2e/screenshots src/themes/icmaa-imp/test/e2e/videos dist/log ./artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build
          path: artifacts

      - name: Trigger re-run manually if necessary
        if: failure()
        run: |
          echo "Run the following command to trigger a rerun which sends metrics to Cypress.io dashboard:"
          echo "git commit --no-verify --allow-empty -m \"Re-run CI tests\" && git push --no-verify origin ${{ github.head_ref }}"
