name: Continuous Integration

on:
  push:
    # paths:
    #   - 'core/**'
    #   - 'packages/**'
    #   - 'src/**'
    # branches:
    #   - master
    #   - develop
    #   - tests/*

jobs:

  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Checkout "icmaa/vue-storefront-workspace" repo
        run: |
          git clone --no-tags --depth 1 https://${{ secrets.GITHUB_PAT }}@github.com/icmaa/vue-storefront-workspace

      - name: Sync config JSON files
        run: rsync -r ./vue-storefront-workspace/template/vue-storefront/ ./

      - name: Debug
        run: ls ./config
