name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  NODE_APP_INSTANCE: "imp"
  NODE_CONFIG_ENV: "test"
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  CI_TESTS: true

jobs:

  # test-lint:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'

  #     - name: Run ESlint
  #       run: |
  #         yarn
  #         yarn lint

  # test-unit:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'

  #     - name: Get repository name, and branch name
  #       run: |
  #         echo "APP=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
  #         echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

  #     - name: Checkout "icmaa/shop-workspace" repo
  #       run: |
  #         rm -rf shop-workspace
  #         export CONFIG_BRANCH=$(if [ "${{ github.base_ref }}" != "master" ]; then echo "-b develop"; fi)
  #         git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

  #     - name: Sync config JSON files
  #       run: rsync -r ./shop-workspace/template/vue-storefront/ ./

  #     - name: Install
  #       uses: bahmutov/npm-install@v1

  #     - name: Run Jest-Unit-Tests
  #       run: |
  #         yarn
  #         yarn test:unit

  tests-e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [ 'runner-1', 'runner-2', 'runner-3', 'runner-4', 'runner-5' ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Checkout "icmaa/shop-workspace" repo
        run: |
          rm -rf shop-workspace
          export CONFIG_BRANCH=$(if [ "${{ github.base_ref }}" != "master" ]; then echo "-b develop"; fi)
          git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

      - name: Sync config JSON files
        run: rsync -r ./shop-workspace/template/vue-storefront/ ./

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Install
        uses: bahmutov/npm-install@v1.1.0

      - name: Build
        run: yarn build

      - name: Start
        run: |
          export VSF_STORYBLOK_RELEASE_ID=${{ secrets.STORYBLOK_RELEASE_ID }}
          yarn pm2 start ecosystem.ci.json

      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        timeout-minutes: 5
        with:
          working-directory: src/themes/icmaa-imp/test/e2e
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          browser: chrome
          headless: true
          config: video=true
          # spec: integration/Cms/**/*
          record: true
          parallel: true
          tag: ${{ github.event_name }},${{ github.event_name }}/${{ github.event.action }}
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.action }}-${{ github.run_id }}-${{ github.run_number }}'
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_PROJECT_ID: ${{secrets.CYPRESS_PROJECT_ID}}

      - name: Dump and consolidate outputs
        if: failure()
        run: |
          mkdir artifacts
          yarn pm2 logs --format --nostream --lines 10000000 > artifacts/server.log
          rsync -avzr --ignore-missing-args src/themes/icmaa-imp/test/e2e/screenshots src/themes/icmaa-imp/test/e2e/videos dist/log ./artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build
          path: artifacts
