name: Continuous Integration

on:
  push:
    paths:
      - 'core/**'
      - 'packages/**'
      - 'src/**'
    branches:
      - master
      - develop
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'icmaa/vue-storefront-workspace'
          path: 'vue-storefront-workspace'
      - uses: actions/setup-node@v1

      - name: Sync config JSON files
        run: rsync -r vue-storefront-workspace/template/vue-storefront ./

      - name: Debug
        run: ls && ls config/