name: Continuous Delivery

on:
  push:
    branches:
      - master
      - develop
      - feature/198003-cypress-and-github-actions

env:
  SUBMODULE: "vue-storefront"

jobs:

  update-workspace-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get repository name
        run: |
           echo ::set-env name=SUBMODULE::$(echo ${GITHUB_REPOSITORY##*/})

      - name: Get commit message
        run: |
           echo ::set-env name=COMMIT_MSG::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Get branch name
        run: |
           echo ::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})

      - name: Checkout "icmaa/vue-storefront-workspace" repo
        run: |
          rm -rf vue-storefront-workspace
          git clone --no-tags --depth 1 https://${{ secrets.GITHUB_PAT }}@github.com/icmaa/vue-storefront-workspace
      
      - name: Init and update to latest branch
        working-directory: vue-storefront-workspace
        run: |
          git submodule init ${SUBMODULE}
          git submodule update --depth 1 ${SUBMODULE}

      - name: Fetch and checkout current commit
        working-directory: vue-storefront-workspace/${SUBMODULE}
        run: |
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - name: Set git user and identity
        working-directory: vue-storefront-workspace
        run: |
          git config user.email "a9.3@impericon.com"
          git config user.name "${SUBMODULE}-releasebo"

      - name: Update to latest commit in branch
        working-directory: vue-storefront-workspace
        run: |
          git add ${SUBMODULE}
          git commit -m "$(echo -e "Update branch: ${SUBMODULE}\n$COMMIT_MS}")"
          git push origin ${BRANCH_NAME}
