name: Continuous Delivery

on: push

env:
  SUBMODULE: "vue-storefront"

jobs:

  update-workspace-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get commit message
        run: |
           echo ::set-env name=COMMIT_MSG::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Checkout "icmaa/vue-storefront-workspace" repo
        run: |
          rm -rf vue-storefront-workspace
          git clone --no-tags --depth 1 https://${{ secrets.GITHUB_PAT }}@github.com/icmaa/vue-storefront-workspace
      
      - name: Init and update to latest branch
        working-directory: vue-storefront-workspace
        run: |
          git submodule init ${{ env.SUBMODULE }}
          git submodule update --depth 1 ${{ env.SUBMODULE }}

      - name: Fetch and checkout latest commit
        working-directory: vue-storefront-workspace/${{ env.SUBMODULE }}
        run: |
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - name: Set git user and identity
        working-directory: vue-storefront-workspace
        run: |
          git config user.email "a9.3@impericon.com"
          git config user.name "${{ env.SUBMODULE }}-release-bot"

      - name: Init and update to latest branch
        working-directory: vue-storefront-workspace
        run: |
          git add ${{ env.SUBMODULE }}
          git commit -m "$(echo -e "Update branch: ${{ env.SUBMODULE }}\n${COMMIT_MSG}")"
          git checkout -b ${{ env.SUBMODULE }}-${{ github.sha }}
          git push origin ${{ env.SUBMODULE }}-${{ github.sha }}
